#!/bin/bash
#Script for deploying the meteor code on the server
if [ `hostname` = scientia-timesheet ]; then
    printf ""
else
    printf "This script can only be run on 'scientia-timesheet.csse.rose-hulman.edu'\n"
    exit 1
fi

if [[ $UID == 0 ]]; then
    echo "Please run this script without sudo:"
    echo "$0 $*"
    exit 1
fi

echo beginning deploy...
echo
echo
echo pulling code from github.com...
git reset --hard
git pull
echo finished pull

echo
echo removing jasmine and velocity packages...
meteor remove sanjo:jasmine
meteor remove velocity:html-reporter

#echo
#echo making meteor secure...
#meteor remove insecure

echo
echo stopping meteor...
# kill meteor
fuser -n tcp -k 3000
echo stopped successfully

echo
echo stopping mongo...
# kill mongo
fuser -n tcp -k 3001
echo stopped successfully

echo
echo stopping node...
# kill node
fuser -n tcp -k 28437
echo stopped successfully

echo
echo starting the meteor server...
#start meteor
meteor --settings settings.json --production &
